### ISSUE TITLE
Packets too close to `max_packet_size` will fail to receive

### ISSUE THREAD

**Issue by jorgenpt** [networkprotocol/reliable#27]
`reliable_endpoint_send_packet` will [verify that the amount of data sent is not greater than `max_packet_size`](https://github.com/networkprotocol/reliable/blob/master/reliable.c#L728), but then it will add data on top of that (up to [`RELIABLE_FRAGMENT_HEADER_BYTES + RELIABLE_MAX_PACKET_HEADER_BYTES` AFAICT](https://github.com/networkprotocol/reliable/blob/master/reliable.c#L798)).

On the other end, `reliable_endpoint_receive_packet` will [also verify that the amount of data received is not greater than `max_packet_size`](https://github.com/networkprotocol/reliable/blob/master/reliable.c#L1048) -- but since there are header bytes added, this can now exceed the `max_packet_size`, even if both sender and recipient agree on this number.

I'd propose a pull request, but I'm not sure which approach is best:

1. `reliable_endpoint_send_packet` requires the caller to make sure they're not passing more than `max_packet_size - (RELIABLE_FRAGMENT_HEADER_BYTES + RELIABLE_MAX_PACKET_HEADER_BYTES)` bytes, so that `max_packet_size` correctly reflects the largest packet to be sent as seen on the wire, or
2. `reliable_endpoint_receive_packet` allows packets up to `RELIABLE_FRAGMENT_HEADER_BYTES + RELIABLE_MAX_PACKET_HEADER_BYTES` bytes larger than `max_packet_size` to account for the header added.

Thoughts?

**Comment by gafferongames** [comment]
I believe from memory that the intention of max_packet_size was not intended to be the maximum wire packet, but the maximum amount of payload that will be allowed to be included in a reliable.io packet

**Comment by gafferongames** [comment]
So this would mean that the error is on the receiving side... please add a test for the maximum packet size, so it can be verified to send and receive correcty and not trigger an assert or be truncated. -- thanks

**Comment by gafferongames** [comment]
Resolved. Thanks for the PR!
